
#title description
title: LizhangX
description: Portfolio
des: Developer / Engineer / Geek

show_downloads: true
google_analytics:

#github info
github: 
  is_project_page: true
  repository_url: https://github.com/LizhangX/LizhangX.github.io
  repository_name: LizhangX.github.io
  owner_url: https://github.com/LizhangX
  owner_name: Lizhang Xie
  project_tagline: My Portfolio

domain: LizhangX.com

notiflight_url: https://notiflight.herokuapp.com
events_url: http://34.228.62.110

linkedIn_url: https://www.linkedin.com/in/lizhangxie/

theme: jekyll-theme-cayman